## List available targets
file(GLOB action_files "${CMAKE_CURRENT_LIST_DIR}/*.cmake")
list(SORT action_files)

foreach(action_file IN LISTS action_files)
    get_filename_component(name "${action_file}" NAME_WE)
    file(READ "${action_file}" content)
    if(content MATCHES "^## ([^\n]+)")
        set(description "${CMAKE_MATCH_1}")
    else()
        set(description "")
    endif()
    string(LENGTH "${name}" name_len)
    math(EXPR pad_len "22 - ${name_len}")
    if(pad_len GREATER 0)
        string(REPEAT " " ${pad_len} padding)
    else()
        set(padding " ")
    endif()
    message("  ${name}${padding}${description}")
endforeach()
