language: cpp

group: travis_latest

git:
	submodules: false

jobs:
	include:
		- { name: "Linux / gcc / Debug", os: linux, dist: bionic, compiler: gcc, env: BUILD_TYPE=Debug }
		- { name: "Linux / gcc / Release", os: linux, dist: bionic, compiler: gcc, env: BUILD_TYPE=Release }
		- { name: "Linux / clang / Debug", os: linux, dist: bionic, compiler: clang, env: BUILD_TYPE=Debug }
		- { name: "Linux / clang / Release", os: linux, dist: bionic, compiler: clang, env: BUILD_TYPE=Release }
		- { name: "Macos / gcc / Debug", os: osx, osx_image: xcode11.3, compiler: gcc, env: BUILD_TYPE=Debug }
		- { name: "Macos / gcc / Release", os: osx, osx_image: xcode11.3, compiler: gcc, env: BUILD_TYPE=Release }
		- { name: "Macos / clang / Debug", os: osx, osx_image: xcode11.3, compiler: clang, env: BUILD_TYPE=Debug }
		- { name: "Macos / clang / Release", os: osx, osx_image: xcode11.3, compiler: clang, env: BUILD_TYPE=Release }
		- { name: "Windows / MSVC / Debug", os: windows, env: BUILD_TYPE=Debug }
		- { name: "Windows / MSVC / Release", os: windows, env: BUILD_TYPE=Release }
		- { name: "Linux / gcc / Coverage", os: linux, dist: bionic, compiler: gcc, env: BUILD_TYPE=Coverage }

addons:
	apt:
		packages:
			- g++-8
			- clang-9
			- ninja-build
			- doxygen
			- graphviz
	homebrew:
		packages:
			- gcc
			- ninja

install: |
	source scripts/travis_install.sh

script: |
	source scripts/travis_script.sh

after_success: |
	source scripts/travis_success.sh
