// Generated by scripts/test-certs/run.sh -- see that script for regeneration instructions.
// clang-format off
#pragma once

namespace pal_test::cert
{

constexpr info ca =
{
	.version = 3,
	.common_name = "PAL Root CA",
	.subject_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "",
	.issuer_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "3862b92bd50c178217374306dc3c3e8b0f309fea",
	.fingerprint = "9805432b65c67e214d8fec85e07750f857edc256",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDmTCCAoGgAwIBAgIUOGK5K9UMF4IXN0MG3Dw+iw8wn+owDQYJKoZIhvcNAQEL\n"
		"BQAwVDELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BB\n"
		"TDEPMA0GA1UECwwGUEFMIENBMRQwEgYDVQQDDAtQQUwgUm9vdCBDQTAeFw0yNjA1\n"
		"MjcxNzA1MTVaFw00NjA1MjIxNzA1MTVaMFQxCzAJBgNVBAYTAkVFMRAwDgYDVQQI\n"
		"DAdFc3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsMBlBBTCBDQTEUMBIGA1UE\n"
		"AwwLUEFMIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9\n"
		"iFxMuWDvbzJKm+FqhIRz8BAIlmqmROcCiMZsGp1yo4FeaMj1OtscUAGaSjsDGnYw\n"
		"cgqzEXW1ZjIgQKWp8V1VDevMKj6yH/GPuEANB9yFJvri4eKFvks/fMZvVji6tMuD\n"
		"f62ma1u/PlBQ5L8kxLJbBkE1dHAqd9fQTxlSz6OBzuJ6I/CA47+xlAbQb+M5GA2m\n"
		"bdMX/4GEelvK+t2lPnDlll28rTLOUqCO5N7qjucQdSjseqH+1wUsCbmbgm1HB14e\n"
		"IJMfq5KtPB+09oJa7U9Wze/Xf7gC6YddOD6YPZMvPZMzUfSZXnmTWJPJCtc1w/9l\n"
		"+9MIysFUzjgc9tnlqO/vAgMBAAGjYzBhMB0GA1UdDgQWBBSdAjxIlLTm7qnC71N1\n"
		"w14g9T51qjAfBgNVHSMEGDAWgBSdAjxIlLTm7qnC71N1w14g9T51qjAPBgNVHRMB\n"
		"Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAPj4v\n"
		"+C0DsAC9VGX0api6G1xpU8zEe15I4rJlIZiyAQtGnhphHG2oVjO1B+ZKcCntYZaH\n"
		"ibAQO/p6ibfk9tkouKLGMTXOrWQ+fvvUKxDU1DWBIej0xSXj7Yh/or7/uZyxwU57\n"
		"8r4hx7fz3Qh/WMXeUhkAfcVtrRuNcpYs/nPiw9IouSZyhrZNY2v7kI9hQ2AGiO/9\n"
		"w9WMS4PSYXIeQHIWyAXx/E1DBpd2yzfZw1JUe+MaXkTrg+8V4R7JpclVWC2FdkMw\n"
		"qohH4q6d82MUZZkj2G5T7M450kEmQtcio5phoh2PJq0VkTPyZNbyYETvGWs8+bL4\n"
		"sCvx96AKFs0ri7yoPg==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info intermediate =
{
	.version = 3,
	.common_name = "PAL Intermediate CA",
	.subject_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "",
	.issuer_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "1000",
	.fingerprint = "d8487d24844bf21917bceb22a12b2a998b848477",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDkjCCAnqgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRQwEgYDVQQDDAtQQUwgUm9vdCBDQTAeFw0yNjA1MjcxNzA1MTVaFw00NjA1MjIx\n"
		"NzA1MTVaMFwxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdFc3RvbmlhMQwwCgYDVQQK\n"
		"DANQQUwxDzANBgNVBAsMBlBBTCBDQTEcMBoGA1UEAwwTUEFMIEludGVybWVkaWF0\n"
		"ZSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJXSAniTiA9uF9k\n"
		"sOn7WreFD4ReGlyymFEhI3DesLKlSYmFSXiYpLIEMoyBvFWQNKzWQzmctqSZt0Wb\n"
		"nGxg9EcCbHzIQm4TH8kBe6v/tI/jFc999DcS3NvyHgxj0rGy91868B9F8cUfPJJq\n"
		"jB9Lb7dV+mETX0XcuQIOxNwKWrxIzvBdfGVk0cnluURdpK6l71kMv3+5i5vPLqG1\n"
		"RVYTUF+Tf51MMN6RHDM58kdQv/HgBVVPGQH7nbvtSDaW4/F7hrZ2FNESGQU1qp8P\n"
		"B1Fuqy4D7XR1eoCi3mu5FbyXm+sC++r2p+0FuzhkPr4jfO+ld0MdAXC7wh4eIBmg\n"
		"ev7P9bECAwEAAaNmMGQwHQYDVR0OBBYEFDw7M4//VkPAWMcK83ECcMmRnePlMB8G\n"
		"A1UdIwQYMBaAFJ0CPEiUtObuqcLvU3XDXiD1PnWqMBIGA1UdEwEB/wQIMAYBAf8C\n"
		"AQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IBAQC5NwOy/rPApu4E\n"
		"CGjaj2IXQxDq9d15tP4O4PoY6vSGGbJn4b5ZiUgkUspX3X6bWqkvPjFVrvRSyvTo\n"
		"lym/GNa9PIY/3cD0LVa6V28s0Z6+e2j286+ZdWon0ErS7QZIJf2ufQkpJfg9q78V\n"
		"cwqDZXXQypKiEVKBcxf9oUnfKutXjpxWPRdDJw6L6V1oOXwHAPCJmD2whrJssuCk\n"
		"8z91mUwDQBG2znTeyVk5jsu/ZUOukMqPEwCxBdPaNaUxxGnlq3LRB7oTpBbYNTP8\n"
		"2tvd2gu6TlBWQ9rf1PblSj6NWkvhb2GJujYLnNSKQETdOIXcuurfLjLxQav4toYm\n"
		"AIurIFWX\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info server =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "CN=pal.alt.ee, OU=PAL Test, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name =
		"ip=1.2.3.4, "
		"ip=2001:db8:85a3::8a2e:370:7334, "
		"dns=*.pal.alt.ee, "
		"dns=server.pal.alt.ee, "
		"email=pal@alt.ee, "
		"uri=https://pal.alt.ee/path",
	.issuer_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "dns=ca.pal.alt.ee, uri=https://ca.pal.alt.ee/path",
	.serial_number = "1001",
	.fingerprint = "dd282dfa0a04ab83d05a5a3e2de9e1faa3afc85f",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIEszCCA5ugAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyNzE3MDUxNVoX\n"
		"DTQ2MDUyMjE3MDUxNVowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCi1eCtUftxESGW\n"
		"gHqYhNkcXdVPJfoI0EVOZxX1ULu31j7oUZzrCnx2gYB9qKnYFMowmwBtMOW3Sk7p\n"
		"Hn2MjgZNg2DC7znFbE81CCy7mbc/kyjJJngIBYUGiUuzhZrswBUeFeqLrVlMRuzK\n"
		"LvJOs/pFn0m8INNz0eiZFKGYqNvC5EY0jU3R0LgVveQNrD11dsr8kTI7hMMQHq/Y\n"
		"B2tAEAA63z8f6KtswIW2q5GhlDFPFfIeO7n59/b6ETe1pc3hF4+hWXWyHiBiru8Y\n"
		"w7maPL2r4B84Qe6XzxqV3V1JYmK/TwWfhxh1lA9zz+/CQDgUPpHSRkiiCagmhxfW\n"
		"mHalR6C9AgMBAAGjggGEMIIBgDAJBgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQEAwIG\n"
		"QDAdBgNVHQ4EFgQUvgh3oYFHU5/f3ME+vsudmd/+VAQwfQYDVR0jBHYwdIAUPDsz\n"
		"j/9WQ8BYxwrzcQJwyZGd4+WhWKRWMFQxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdF\n"
		"c3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsMBlBBTCBDQTEUMBIGA1UEAwwL\n"
		"UEFMIFJvb3QgQ0GCAhAAMDQGA1UdEgQtMCuCDWNhLnBhbC5hbHQuZWWGGmh0dHBz\n"
		"Oi8vY2EucGFsLmFsdC5lZS9wYXRoMGcGA1UdEQRgMF6HBAECAwSHECABDbiFowAA\n"
		"AACKLgNwczSCDCoucGFsLmFsdC5lZYIRc2VydmVyLnBhbC5hbHQuZWWBCnBhbEBh\n"
		"bHQuZWWGF2h0dHBzOi8vcGFsLmFsdC5lZS9wYXRoMA4GA1UdDwEB/wQEAwIFoDAT\n"
		"BgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEAZRp15vVQmhLR\n"
		"uB6CU9ahN70WNgKGTr9d/9bfEduqeazvrV0KvUnIUvSbbApcCbynu98apfsO8h+h\n"
		"rsxhQHdsxVilOJrXUKAHWq7WRDEborhZYoKdzFhaTXsgEA5L7UaoNoIczUXFb73s\n"
		"P7ZYNeV4yiYTy4oE29WfEJCvhzJgMD5p+O6KpgIIIkzazCUC4hol2QqD+UFfbIox\n"
		"pOPm0X438AQ+ykn8ljFi6sP8vGt7FP/SO6tqh465baVyKA1ZNgTYpUrZOR6dCN2c\n"
		"e8p/IA7N7w0y/6vlLyttqa4JYz6QBRpsJUoeIhJxx9WLahC/u3v7bNlxtj6vWMvJ\n"
		"+B9hHbWAag==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info client =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "CN=pal.alt.ee, OU=PAL Test, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "email=pal@alt.ee, dns=client.pal.alt.ee",
	.issuer_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "1002",
	.fingerprint = "a8e2e18c76af5c69229214d2f4c13e426d6034cd",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIID6DCCAtCgAwIBAgICEAIwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyNzE3MDUxNVoX\n"
		"DTQ2MDUyMjE3MDUxNVowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmj20T2rwbm3Yz\n"
		"DQeUXNxlY0LfgXcUlHGEyAuaI/+TSjtaho4CkrSTm6jYjxtvR8GgwUHOr1MIJj7o\n"
		"0dgQxDJvVY2kXCzqNWsiDeGLUJSfYjvjLoJyoKqEoqBc1Z15sEqlZsMCbpxhWmVO\n"
		"XxEPlpBibMTuxZQyV9aK/6Tqlz9+VJWPn1IuaREO7uJQ+UYaxagmXKx3tHfd3e/2\n"
		"U4DxLoaLV1LFhK9EowQ4TPiK8o7Yu4b+209QcvA3u8oMVRgq/UtIgUP/uIVYpQft\n"
		"iPcs6G+AjWW6jff9a5W6vW8ABMkNkAqBTXgRzxF0SI5Q9ZIqxwYbkepldaH8sNLg\n"
		"irsgFy4TAgMBAAGjgbowgbcwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBaAw\n"
		"HQYDVR0OBBYEFFVEXjl9PpRgcpLLlbogPwilDVlrMB8GA1UdIwQYMBaAFDw7M4//\n"
		"VkPAWMcK83ECcMmRnePlMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEF\n"
		"BQcDAgYIKwYBBQUHAwQwKAYDVR0RBCEwH4EKcGFsQGFsdC5lZYIRY2xpZW50LnBh\n"
		"bC5hbHQuZWUwDQYJKoZIhvcNAQELBQADggEBAF7BGyDBTkRQ1+tML6IfoLnAw4bA\n"
		"kTImiksJM53gtN4ID8cP2lzEmjKO0UBwsj7sV8pM4EKAg1ZXQ+hgXX7IMayGqa/W\n"
		"BwWgB+lCo1PSs7SRdTnKirlATkzzaAV5kdtRETp3+jk3JOtATLW+EDeczQ6e9IiW\n"
		"zXtO0+0uIo0pdnef8kvXvSEQ4OErJe0vkF7/3jtiBPl/ommCmlkDkPitpn3fi1Lj\n"
		"Gbrx0yjvgZ7qQh4h1m/Sq6P9RQTZRc/mAnGiF3eIdEKA4V8jyHmWDNlRvqZyTIYZ\n"
		"UcoNJ9sVxDZnqt/6349iQDOQ2hcvm/PktM+jAhlYztI2vSniVxcc+Sju6gI=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info self_signed =
{
	.version = 3,
	.common_name = "Test",
	.subject_name = "CN=Test",
	.subject_alternative_name = "",
	.issuer_name = "CN=Test",
	.issuer_alternative_name = "",
	.serial_number = "3a25b2857fad9fcd1c97454cd0fca4025e3b3069",
	.fingerprint = "cb62c7c324c4741a4cdc1acf616af6860248257a",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIC/jCCAeagAwIBAgIUOiWyhX+tn80cl0VM0PykAl47MGkwDQYJKoZIhvcNAQEL\n"
		"BQAwDzENMAsGA1UEAwwEVGVzdDAgFw0yNjA1MjcxNzA1MTVaGA8yMTI2MDUwMzE3\n"
		"MDUxNVowDzENMAsGA1UEAwwEVGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\n"
		"AQoCggEBALJ2M2crQsXwttrqfBCMSG8lt1aCUM/Umc+sW9DD1Nl2YrMduHCHXGrZ\n"
		"ZBsX9xlwKtNfHcfs+VOXtiRSVFyzekLYOuFcfbyWcb2MVt6pu9swKpWiwvzaor3l\n"
		"EXxj30TsI4woqBXovwvseSC9eGd3gpq/2+w+RzlmGThJN4jZUQrxhUwu1fXJ3DH5\n"
		"7Oxp/sAJ9uN+sU4PbBQk1L4rjgm1g7s5QfXgsK5xnyJVW8RbK+MijdEVyheUmElo\n"
		"5jApYf3SHwC1G8l5edABPqwT2dQVfJlSw7ytVTlTU+mMC/E+bNbX2ehwG9Rl7Xsz\n"
		"MD7OgcuVFOFDd6lH12uMVofhuCNZz+sCAwEAAaNQME4wDgYDVR0PAQH/BAQDAgWg\n"
		"MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQUPJe2Ol4L\n"
		"0i2cUTZfJ5Ot/m7IvnMwDQYJKoZIhvcNAQELBQADggEBACXEdK3w3HR+sXgUD3ab\n"
		"R4H7GiFn3+jcfSiQplOMJahoNxvCJKNoJrs7BHX2A/C4PDxwYJkYdxTHEPsyfEaM\n"
		"O3Xroz8A2t9L0Y2mwL4dr14v+xhUvtZxLHFOjCNRkPRCNef6OK/L5fjcMJLzUak7\n"
		"zen5XOg4+C1B//o8Qob1kGFhGIH2sCH0OWYoUpxlt7AmKu28k0TSX8E8RCZVWMN3\n"
		"DowN3isHjr4jlKi73K2a9f50RvaX74INYow9X1uN2RkFNLafPPr+Ivk/+/w2CEdE\n"
		"0tMd7L26INmZ1EOHEUvGkebUkahgD7iF5q9rCSUoT2kyTDzgSIpBy/5gmJrjpLzw\n"
		"8l8=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info no_cn =
{
	.version = 3,
	.common_name = "",
	.subject_name = "OU=PAL Test, O=PAL",
	.subject_alternative_name = "",
	.issuer_name = "OU=PAL Test, O=PAL",
	.issuer_alternative_name = "",
	.serial_number = "103670824db6549003444972adc91d63e1d21762",
	.fingerprint = "8916d6962538ba09b4644e7989b1248778ff83bb",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDIjCCAgqgAwIBAgIUEDZwgk22VJADRElyrckdY+HSF2IwDQYJKoZIhvcNAQEL\n"
		"BQAwITEMMAoGA1UECgwDUEFMMREwDwYDVQQLDAhQQUwgVGVzdDAgFw0yNjA1Mjcx\n"
		"NzA1MTVaGA8yMTI2MDUwMzE3MDUxNVowITEMMAoGA1UECgwDUEFMMREwDwYDVQQL\n"
		"DAhQQUwgVGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKUF6hET\n"
		"o0QZQt106ITEpC1oyuNGTYgDpMRJMjyeOLv+bQXRaDUvCdC8ebW1twsszjGKzkPP\n"
		"Gb0Vq9PxxxUbagvItN+5dHGGVAF96mA/3ItqLkusm6ygK+wHvGfvjR78aNrolYMw\n"
		"y/wLllzRi2cdSexOR1tUuNN5z0Mxg6VJJW+WRl1nhkVRJPezfkrfRw0k8URr6iaP\n"
		"8sy2hAjfaRB+hinxjqnqTJhP29x+CHVc+60xavUNjaCyFDVvLcSysr4uslxqmW7K\n"
		"OwNGx7nVOdAciQ1/ypGjWesQbxY8JLJ+Z4o/twD0LhDHVBBWy7/ofcTqtk4eg9+a\n"
		"zPDma5PlMhS1tLsCAwEAAaNQME4wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQG\n"
		"CCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQU2nc6KQGggUMrxxJLLjsAs7MB\n"
		"2hgwDQYJKoZIhvcNAQELBQADggEBAAsR1RYeIHSefjo8XSX0joGC+FuiHcEMmT8r\n"
		"h9qrWzmuJXpMoCGKI6zB98fhnrLT59EXzSKaunvHAdhAlbqCIxS2kmy0mNebrzmJ\n"
		"xwDVi9L0Wyes7ptdgC0LmHeuJp1XACSnosHaE4F2XBGOVM4LbFK77FOalLYvApj0\n"
		"Ai6GexKwkyZOnhcHF8lLSZSdkeBySQySyBQMaKSsXsawNYAfT3PbJPyju/PXxy7w\n"
		"JKQfiLIMVrqOtvlzbEH6BmL9L3ANFkR74hG9jWi9pqeeEzzcKM+EZn4Oe78cBOXY\n"
		"gB6TG3vgKT0LUBVupVXj9Bcb9dCXExmrtrQw/jiS3xa1Q1z7PYQ=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info empty_dn =
{
	.version = 3,
	.common_name = "",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "391e1b5f197bdf6d9b6cc35d93aa9454d948281d",
	.fingerprint = "975771539b4424ddda79a0cab42b8f1cf8077098",
	.size_bits = 256,
	.max_block_size = 72,
	.algorithm = pal::crypto::key_algorithm::ec,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIBVDCB+qADAgECAhQ5HhtfGXvfbZtsw12TqpRU2UgoHTAKBggqhkjOPQQDAjAA\n"
		"MCAXDTI2MDUyNzE3MDUxNVoYDzIxMjYwNTAzMTcwNTE1WjAAMFkwEwYHKoZIzj0C\n"
		"AQYIKoZIzj0DAQcDQgAENRRFPgZGUxDbwbMRbMIImJyrLWsXVTJhGC3fEvnVbOVS\n"
		"bwHtd/o/8WC2JhjY3M/pOHV/wnH26Sm0Ys1ZCM6XoqNQME4wDgYDVR0PAQH/BAQD\n"
		"AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQUTiJ6\n"
		"TexVzGv5C2vnnvAJhe6UGw4wCgYIKoZIzj0EAwIDSQAwRgIhAP7R5g8/uhftdgT3\n"
		"KU0E4zB8zBGUvUuEn3na4e8t9d2OAiEAhIY6HFLTdHNa3KPkMwNemWhDwtFivvAi\n"
		"NP4bQRmmP8I=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr const info *data[] = { &ca, &intermediate, &server, &client, &self_signed, &no_cn, &empty_dn };

} // namespace pal_test::cert
