// Generated by scripts/test-certs/run.sh -- see that script for regeneration instructions.
// clang-format off
#pragma once

namespace pal_test::cert
{

constexpr info ca =
{
	.version = 3,
	.common_name = "PAL Root CA",
	.subject_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "",
	.issuer_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "c84c80009df44b12",
	.fingerprint = "faaf17b11393926d25070644c1e0da4b1d6b767a",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDjjCCAnagAwIBAgIJAMhMgACd9EsSMA0GCSqGSIb3DQEBCwUAMFQxCzAJBgNV\n"
		"BAYTAkVFMRAwDgYDVQQIDAdFc3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsM\n"
		"BlBBTCBDQTEUMBIGA1UEAwwLUEFMIFJvb3QgQ0EwHhcNMjYwNTI4MTgwMDIyWhcN\n"
		"NDYwNTIzMTgwMDIyWjBUMQswCQYDVQQGEwJFRTEQMA4GA1UECAwHRXN0b25pYTEM\n"
		"MAoGA1UECgwDUEFMMQ8wDQYDVQQLDAZQQUwgQ0ExFDASBgNVBAMMC1BBTCBSb290\n"
		"IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAulYE1tXYYC2fWF+i\n"
		"Pra84O4rm8sgF0gxEnm/8NjswqalfhOipmhvKD/+CqHCYUcs73vTHNOthN+/Eyaa\n"
		"Mubvg87IsabpW21SD4sms9g14PRgTE4E2BXi8ktT8W2/5JZUTh4Cu6Dc7Aehk/5+\n"
		"LytVLtcw0XwFzh91WtoyRTtaAV+mNc4Wuxg8fXKVqrrLSE74rnFIj3+x6gF6hH62\n"
		"/EKMUWRm04M/pjLZI79tqlLqu9jLQ63ZDdTQv6XPR5lKw6d7j3N6QX7/+/WJinQ5\n"
		"aXU381A4O9UDbLvLh2bDRmBvAymY1H4V3mr++svv/2XwgHB64fs4028SfJLL4LaR\n"
		"dOJS8QIDAQABo2MwYTAdBgNVHQ4EFgQUUc+IL43vvZoQsGb0nxUnwmgLzIUwHwYD\n"
		"VR0jBBgwFoAUUc+IL43vvZoQsGb0nxUnwmgLzIUwDwYDVR0TAQH/BAUwAwEB/zAO\n"
		"BgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQELBQADggEBAEJCOmNA8H8akfaqyb24\n"
		"jM1EPPl8meBRR8kkPWD0EBGNUIFwGFiFGDzfzE0jmfDIEL1JZyrpM9L79SCDQgCV\n"
		"OaYNGWuO+CRnT9vc1Rdqqwg055X2tT/kcVubRhgFPc3kJYiHjLriEfuDDsoaoT9E\n"
		"yhqnkdojNYQsYA9zrtoynYWn0TA399p7DPkBv7vHq7vMzX3yXMBHMrR2DHh5LHGb\n"
		"nCgADhyONQe3YaaOBFc1sGD7XAA/vabxig844zPXbCZsLFBC0eJCF6lLqBUnCVmK\n"
		"pLI1tqOAiAcRN0B8FFRtjKQxCT5oiaqx0vF+OisfqjEv7jT4++bIxdhYQZIJU9bj\n"
		"MeM=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info intermediate =
{
	.version = 3,
	.common_name = "PAL Intermediate CA",
	.subject_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "",
	.issuer_name = "CN=PAL Root CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "1000",
	.fingerprint = "fa7932ba7c77597a0b22f59570eaeda4341c5828",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDkjCCAnqgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRQwEgYDVQQDDAtQQUwgUm9vdCBDQTAeFw0yNjA1MjgxODAwMjJaFw00NjA1MjMx\n"
		"ODAwMjJaMFwxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdFc3RvbmlhMQwwCgYDVQQK\n"
		"DANQQUwxDzANBgNVBAsMBlBBTCBDQTEcMBoGA1UEAwwTUEFMIEludGVybWVkaWF0\n"
		"ZSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPedajA+RAh9+YEW\n"
		"rTZNhkokId8ox9RZ3YUs2V6DIo37yxETRca5LglvsMpZ5yp2CYfW6N89oMtYB0sw\n"
		"/X/tSzqafmAP0mZKPCFp8HKDOCDdZ2ArEAQBIlfSgZ9UVZjky85ynDhcHrEDPdbY\n"
		"bQ2aeeaMjAmB/wX5xite73FUwdln3NKK3cvHTCEoZ7ikcRpENax0LzJ58yEKcwBB\n"
		"bC03gW7+saJfqaSn3eFzEiATCANCxDmaMBpz8SlW4g0k3cMlQnR6MigJFQ6SRu7N\n"
		"19q6ewbpjGgnHe6YYnuYYIJ2OYRORqi02HO8x9OEJl5PVZHBXTWgZE0mDq/hAPzK\n"
		"DdHIvYkCAwEAAaNmMGQwHQYDVR0OBBYEFItUP5Y6Wrt0JkgDTlirw6duUEp8MB8G\n"
		"A1UdIwQYMBaAFFHPiC+N772aELBm9J8VJ8JoC8yFMBIGA1UdEwEB/wQIMAYBAf8C\n"
		"AQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IBAQAi5jRP81eIIXCV\n"
		"EzcEN1bwz5jHrX3us26lVZnxBn16FXEtf0/xilB4cI+ae+d52Bgcx3XKZni4VcP7\n"
		"B57ApSt4fNJecOF709eKdNJlmWewVnv69DXOhyVEMVBZnz3SR1WfNYEdAotGtd40\n"
		"qPU0vQPOuxI0F2HopDMJ9PRjfCpgt80ou/479inB6CRk9mg9KGNc5LG7PFylkfI5\n"
		"+r5GgcDPw9XytH3P/TbjHv725YdDSZHTMFqkioTqKMRmjTsojq5mvGzqMGBKIhq5\n"
		"xB5ENqenu6KoeHNaIAzL7jW5os5MFwynOZXyBHhRKEKel71xlGD+fSYQU9R9+GXw\n"
		"R8ZaT/nS\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info server =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "CN=pal.alt.ee, OU=PAL Test, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name =
		"ip=1.2.3.4, "
		"ip=2001:db8:85a3::8a2e:370:7334, "
		"dns=*.pal.alt.ee, "
		"dns=server.pal.alt.ee, "
		"email=pal@alt.ee, "
		"uri=https://pal.alt.ee/path",
	.issuer_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "dns=ca.pal.alt.ee, uri=https://ca.pal.alt.ee/path",
	.serial_number = "1001",
	.fingerprint = "c6b1d374e7670c437c681b5bed21a11eaccc0eae",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIEszCCA5ugAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyODE4MDAyMloX\n"
		"DTQ2MDUyMzE4MDAyMlowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5MmI2YVAPRY0F\n"
		"zUSE3NJqKV4dyTpexYAHML4azcERq2dcsgSExu+CjTmfa1FlSZFhxBj9B2ircZ2B\n"
		"r7A2bxnzxlbujoMCb+bryEFnxnzvhy8XxxLDE4UWbSDAJA7Yu2qHVMS2O1olQfmN\n"
		"WouEWQ8oL+YyOSxCYIpnRF+yhhy9WoDwvYFVF+SqvgCwRy9SlBbthnwdD/7ELiwF\n"
		"u1KpnxrTLqmieP/t1gw4BwZUPlMb4lHiETZI011IBywHR7T2l1W7HvcOAL4Y7DKW\n"
		"gtXhjl3xNvK5pleqtWzeYz84pOUa+Jk9BWkkSBE+3KezUP4QDef6DYM67TRrSyHm\n"
		"Rrl7DeFZAgMBAAGjggGEMIIBgDAJBgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQEAwIG\n"
		"QDAdBgNVHQ4EFgQUFl9d/cN3ssW8oLLnYV368Ehtka8wfQYDVR0jBHYwdIAUi1Q/\n"
		"ljpau3QmSANOWKvDp25QSnyhWKRWMFQxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdF\n"
		"c3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsMBlBBTCBDQTEUMBIGA1UEAwwL\n"
		"UEFMIFJvb3QgQ0GCAhAAMDQGA1UdEgQtMCuCDWNhLnBhbC5hbHQuZWWGGmh0dHBz\n"
		"Oi8vY2EucGFsLmFsdC5lZS9wYXRoMGcGA1UdEQRgMF6HBAECAwSHECABDbiFowAA\n"
		"AACKLgNwczSCDCoucGFsLmFsdC5lZYIRc2VydmVyLnBhbC5hbHQuZWWBCnBhbEBh\n"
		"bHQuZWWGF2h0dHBzOi8vcGFsLmFsdC5lZS9wYXRoMA4GA1UdDwEB/wQEAwIFoDAT\n"
		"BgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEAhPtYCISfWvgQ\n"
		"5PzgalnJRhxfhWf5TsoFAV5iH4BLe+H3PSfxj+s5LjHkx2JTvl6wAulcBXdomBZe\n"
		"R40lmftDn2GBKDCfDSbopo9034eiA+8D6sEVkTSqLIhOC0sbmeArHa9HNjBD48jx\n"
		"8Mvrmi1ts75N52E2tAI/3hwDlbyz0rEOpkLvFbftllXhbFJOGe+Ft2Q3PPWtdMlf\n"
		"0iGAJuGjW3FHUutr2teak8Q52S5um3DuaStQwiFfX5S9n73Cq9Epw3ikku/A4yO/\n"
		"W8xL/85lqsF5RlHU45WxQEBWkAh0mfZ6z/+BompaCAQpdvTK4QruEtbeGwo1iUKV\n"
		"uMRR4A/mNA==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info client =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "CN=pal.alt.ee, OU=PAL Test, O=PAL, ST=Estonia, C=EE",
	.subject_alternative_name = "email=pal@alt.ee, dns=client.pal.alt.ee",
	.issuer_name = "CN=PAL Intermediate CA, OU=PAL CA, O=PAL, ST=Estonia, C=EE",
	.issuer_alternative_name = "",
	.serial_number = "1002",
	.fingerprint = "2ec61141635c317f7fc0300477f13efb5e89910b",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIID6DCCAtCgAwIBAgICEAIwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyODE4MDAyMloX\n"
		"DTQ2MDUyMzE4MDAyMlowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCl1HLkIduqRww\n"
		"BCs2wpAt1fhY+SntMF8wPVPiNfM9YmZcWhvy8ifS4R7GsbBTMTVeXziYHHQzVIXi\n"
		"7D0kAiv2tZ8YwR9lE7opAWX/J1sivpz1WV/AYT9eKjkFT6OiJNzbyrQ4zMZEsNsP\n"
		"DpquRx6V9XnQgxWaKMbLvoWvpieyHt1CPMOx2kSG7v8TdEe+LERTlsuAmdjtYbV2\n"
		"HLTM/TbCTvyClbI8r7dUjLFShaXReePVtqTx3xsp8R+ladJXGdeftKW9wceel/Hc\n"
		"Y9EkwwhTJU3yaWuBhDv1+tB/MK4e3GQwFLvPoThI2fnbqv4Gj++XEce8tVnsv2Jo\n"
		"tgCq1EJVAgMBAAGjgbowgbcwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBaAw\n"
		"HQYDVR0OBBYEFGyVMIhde3pc9JQ4+VHeJQR6fOIRMB8GA1UdIwQYMBaAFItUP5Y6\n"
		"Wrt0JkgDTlirw6duUEp8MA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEF\n"
		"BQcDAgYIKwYBBQUHAwQwKAYDVR0RBCEwH4EKcGFsQGFsdC5lZYIRY2xpZW50LnBh\n"
		"bC5hbHQuZWUwDQYJKoZIhvcNAQELBQADggEBAGIvk8kxmVzu5oEbqe+4i1z2mur/\n"
		"2/0Ssjb74rntaglEBrt0WT6kEacm3OhpFjsgy4kc36tv5juASpNiDuYuwS3imvq8\n"
		"axF4eF++GN0adZvnCtqpdoMgKhvJHZIUqlnGtpUFvhJ4+aVpOGKTF+Td1W+n7dxi\n"
		"/PF4inJ7uAgFTNs/1AywYBZbSxMEjTX66scZtjinDCeX6+Ir05Nbgtk9aOJ0Eibj\n"
		"90XhHdN5rascTPLQv7iPV3ozqRtH9IbRF8aetAci94D1UI7I8fdNj11V8Tfu9sNs\n"
		"TnTh3DzXadUtMjHRsvFbjTwL9yyk7JBiWbRrzfue9+vH72KFY3u01gcvqZw=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info self_signed =
{
	.version = 3,
	.common_name = "Test",
	.subject_name = "CN=Test",
	.subject_alternative_name = "",
	.issuer_name = "CN=Test",
	.issuer_alternative_name = "",
	.serial_number = "885d306536bc7454",
	.fingerprint = "28d69e84c105fb22da94e7e955d5c7a465df5e10",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIC1DCCAbygAwIBAgIJAIhdMGU2vHRUMA0GCSqGSIb3DQEBCwUAMA8xDTALBgNV\n"
		"BAMMBFRlc3QwIBcNMjYwNTI4MTgwMDIyWhgPMjEyNjA1MDQxODAwMjJaMA8xDTAL\n"
		"BgNVBAMMBFRlc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRlwIq\n"
		"06Ek5tJMg39Lh8q6E0roqCq9aN7phRh2u3juGvdm/1olzJcTREnW16kTVLmT3eth\n"
		"dWfgSRUZqnmZ/XzCfku80edkEcT1UtGFf0IjJmGRTOr66dcvsxYSKCA4iJLCGWd6\n"
		"h/9dsvq+xkPNtJeDBTj88Lt7t798RA4Xj9NeHPdPfTBWpYYjMA0Vm5Lew5A2qc6k\n"
		"ok71gIxRc+LqjLkmsfKPeKrfpYAMW9j0N5r10N2PCH+fMQmHtydMTqbZcg56GRiG\n"
		"OphPdNJZYRy36lT7n4lGmNftDrrRxC5WGRwNuiBvz7qVZCXKC2LLZk4nGQc3tutJ\n"
		"D1pRKZWSHqm6OgEnAgMBAAGjMTAvMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU\n"
		"BggrBgEFBQcDAgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAJTxEsGhJlpW\n"
		"fenC+Iz6gwL2e+SkQic/WmNjTE1QTsJSjlDNFvQalrtklvnbxrn3Zm8vEuveIEwO\n"
		"XRQdtWREHURcI5hciAVDK4IgPeOsshSjhRdUwR1jbGVKJtIytmFzE3J42Lt3jDCq\n"
		"ZgXiEd09ttiD1IfQDm3N5DuUjJ8akwqcc83x12McDwI/Oq5OyVH7Pe8Jx0Flc0A/\n"
		"PxN1wWdwVYMJ6N/yKEtHL6MGR6l4bNKHI27cPXYmFMSEJUFch1nytIyJ7UK9WXfK\n"
		"0qQ2FoG1mnMAiQP1ll7l4a2k64mGZmjTYILc2AdlIIOFABY3lojdqHYl7RJB211c\n"
		"rMhyOMfuBV4=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info no_cn =
{
	.version = 3,
	.common_name = "",
	.subject_name = "OU=PAL Test, O=PAL",
	.subject_alternative_name = "",
	.issuer_name = "OU=PAL Test, O=PAL",
	.issuer_alternative_name = "",
	.serial_number = "dfcb4da22c831d95",
	.fingerprint = "a86716ee68b6bff4ee399773ce50d86831876545",
	.size_bits = 2048,
	.max_block_size = 256,
	.algorithm = pal::crypto::key_algorithm::rsa,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIC+DCCAeCgAwIBAgIJAN/LTaIsgx2VMA0GCSqGSIb3DQEBCwUAMCExDDAKBgNV\n"
		"BAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QwIBcNMjYwNTI4MTgwMDIyWhgPMjEy\n"
		"NjA1MDQxODAwMjJaMCExDDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3Qw\n"
		"ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxuj4KcwQYGQ+f7zNfm2NC\n"
		"TuXQcFqkEc+U+USyRH8XFE/n0IMgVZ6nitc+zIhy2BLIRDO9ZRaPuYstgnX8GcMJ\n"
		"KjgHxnlY7hIxVoCQc1ldwAevRiBKFzJ/yZEzBuA3z4jseC1mzTgyp21Mc+aK9j2W\n"
		"JN1+UEzvBpOwTBzIhvUgR6rhq9DlFwXoODacyFnPtvPF4C5PpBd9pXWAqS34JFlK\n"
		"r61bcpochkQibvya5Dy7UlBifYef4TYY7Xp7XmVwEwo4fNDR/0uvTXK4AFbK8Ni2\n"
		"HMog5xIYGNzZwqtOPwaJpTXDeb7SgvqM3/OYeLghRiQGR5SbLAoS21N6p1p1vO7z\n"
		"AgMBAAGjMTAvMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYI\n"
		"KwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAIf1f9nKtH+nao7uK+iXHyvKJxWA\n"
		"o8GTC9fjTMn0FD+yqyaaNk8SPuXWQKqLrefOAekilTDbFQOUHAf71qXuAZwwRMFL\n"
		"RxBMmpetrnlHul2F6birm74mikpSmHHzIPPQbL1CWPi01J3IJcIpJ95L8OUbeQdB\n"
		"B1l+4IFGY4Bxxnq1kR0Q71idbYXyfPQPc62sT1L3jVVKinHE09dR3159KAXf9Iiv\n"
		"vSZIQLh8MngFhNsXeOCCULLMp/K5jpM9f+UUSsxqUj5SGk8wSMbCuuv9sE6u8GLj\n"
		"LwwKGJ4ixXrnKsl2NhiZYlYz0DSZbn8d0Vk78ijKNTo8EVckWjdeaNnuFXU=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info empty_dn =
{
	.version = 3,
	.common_name = "",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "b0365c0e2588c550",
	.fingerprint = "5cb8c58b18780bfcfefab306d70b3eb18895b7b8",
	.size_bits = 256,
	.max_block_size = 72,
	.algorithm = pal::crypto::key_algorithm::ec,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIBKTCB0KADAgECAgkAsDZcDiWIxVAwCgYIKoZIzj0EAwIwADAgFw0yNjA1Mjgx\n"
		"ODAwMjJaGA8yMTI2MDUwNDE4MDAyMlowADBZMBMGByqGSM49AgEGCCqGSM49AwEH\n"
		"A0IABDEz4jDj3J06rGZhJ3g3n68GvH6rCk62S8By7OowSpya6Qx4YeyGIhIfqu0E\n"
		"OZlyYq+arDQ7b4zZcgxijk0Y82GjMTAvMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUE\n"
		"FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDSAAwRQIgNVzIxZ5L\n"
		"BIAcT5m1o/tO/w6l8cnleiOyAXSk+HZunLcCIQDcj0O7uXVIU7biCVWqCMwGTIf/\n"
		"3LX5ESlJSPxzB8N3Zg==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr const info *data[] = { &ca, &intermediate, &server, &client, &self_signed, &no_cn, &empty_dn };

} // namespace pal_test::cert
