// Generated by scripts/test-certs/run.sh -- do not edit
// clang-format off
#pragma once

namespace pal_test::cert
{

constexpr info ca =
{
	.version = 3,
	.common_name = "PAL Root CA",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "61134f4dbbbf7fa84cfa74235b87704821aa0d34",
	.fingerprint = "ea7ca7bb4e1bcf427e2f3a5070bd4fb1967812fb",
	.size_bits = 2048,
	.max_block_size = 256,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDmTCCAoGgAwIBAgIUYRNPTbu/f6hM+nQjW4dwSCGqDTQwDQYJKoZIhvcNAQEL\n"
		"BQAwVDELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BB\n"
		"TDEPMA0GA1UECwwGUEFMIENBMRQwEgYDVQQDDAtQQUwgUm9vdCBDQTAeFw0yNjA1\n"
		"MjQxNDI1NDhaFw00NjA1MTkxNDI1NDhaMFQxCzAJBgNVBAYTAkVFMRAwDgYDVQQI\n"
		"DAdFc3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsMBlBBTCBDQTEUMBIGA1UE\n"
		"AwwLUEFMIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCW\n"
		"VUuvI7HPqbnP3rx0bE8ADXC9cg8OmTNzHiDRmGNN9sYGKxrS8jbhDfnRED9M7ePz\n"
		"Z+1phuQtSrO6Q9sol9eRqquOgtL5DhHGQ/8iJSpitLCuMItAAHI2PfHB5dzEeie+\n"
		"PgyqAZVcGN+S/GZ/2eWJE/rhGur5Lu0fBNM8yTsfwIbfsaAJWF5RktcL7oHPwW0u\n"
		"91FswgkmIHbvmtYNeetHQMv6EM2xzQVgFeXufZ3CsDrThBbCkvsj/PA35w64dCnR\n"
		"eqclM6dynDF/botvII6Lr68OewCyjYPg5yqTqeUSyRoqKLT6JlthYIih0NzxaQcF\n"
		"m2d+2DGWmvPd6Spb4hhBAgMBAAGjYzBhMB0GA1UdDgQWBBR4I88Fr+PpwxqLb76A\n"
		"eYej49cDPDAfBgNVHSMEGDAWgBR4I88Fr+PpwxqLb76AeYej49cDPDAPBgNVHRMB\n"
		"Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAhv8f\n"
		"vWlzoGG4NwTHHoWewfyrK35mhdR1lxWBlP2DQPvzjS6EmGfZiW16w1sEt3b6cMmV\n"
		"7KagTWyCajvnCLL9T95cX/sffhxNMG4NnBqEZTbJyb9roccp/LRyrUdyXyz4WYhp\n"
		"lBGhfINsxTIYC5SoKW1/kg6swGXo7zF6TQYHx7RkctEWCOQnJpDnzqAwMNIbSI0K\n"
		"9B3CqS8wzk1E3zkFsbGVWGqGK48QqdGL1VBVLYO2WB8xe1+F0UG+JsQMm0T5PgPA\n"
		"F0h3Dv6O4IOjv0tv8qKDb+jtBP1FptelGgaUvF81eyBtm2TDYqJD+jhspefVj8WZ\n"
		"iC9Z0xcSqpmJwWsPKQ==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info intermediate =
{
	.version = 3,
	.common_name = "PAL Intermediate CA",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "1000",
	.fingerprint = "0aa4a4a5f4e5c266bf8452131ba88873b2f9b702",
	.size_bits = 2048,
	.max_block_size = 256,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIDkjCCAnqgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRQwEgYDVQQDDAtQQUwgUm9vdCBDQTAeFw0yNjA1MjQxNDI1NDhaFw00NjA1MTkx\n"
		"NDI1NDhaMFwxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdFc3RvbmlhMQwwCgYDVQQK\n"
		"DANQQUwxDzANBgNVBAsMBlBBTCBDQTEcMBoGA1UEAwwTUEFMIEludGVybWVkaWF0\n"
		"ZSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK/oDwXoG7N4GukY\n"
		"eKdN2OhgCDs9eZURXQ//dO8lnNCP+DxN6G9gF90Ik6/Jc0FUjN7MBYZt38siS2cR\n"
		"e75yXfGxwX4No9h0jEh9gA4d7H6CW4S7hzqes38f3IN6gVLUP4Bu8wKueUUezI1H\n"
		"TGSBEp8awpSeX4Dzv4OKBrDEbo1LhlRBOKWonDLifZzWZfU7+NuSC9iI9pVkehSK\n"
		"ysRhhp5sSO5zpTrhQrpuySg9/Pf8FxiSTTROxn4aupl6hgCTBVuLxCYpatHqIZl4\n"
		"IPPL0THfDR2KHvCvUeMQbx9NxQ/QbV0Rt/1PHNbngz7UXfnHXsnVp5DnBtzdyNcL\n"
		"JUYfIzcCAwEAAaNmMGQwHQYDVR0OBBYEFCTpCkPGQ1yxAcIKz3o8XAaAH1HWMB8G\n"
		"A1UdIwQYMBaAFHgjzwWv4+nDGotvvoB5h6Pj1wM8MBIGA1UdEwEB/wQIMAYBAf8C\n"
		"AQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IBAQAN9h/i97a9MLos\n"
		"ZcFnplOK/pZV8g883yAbBlr6YeMmpdgQizfcyj4+dKwr/MZVItWwcS99PUf1cPl8\n"
		"aUVH0LAXPiLVvhlsvlMA7Ty/15lg+MAYcOQWbDogCN91ASlVEmeii8c56OfECfcu\n"
		"qmYsTcomaqp4kWigrWyJaM8YPXM6wmDZjsjNUY4CcdWsEgpGBoUOFaicOYF4wb6n\n"
		"NdpeSFfY+XdkK2fvcnQTgaCqMvFLPvGCiRVKOFiaUMfXMKnNM3lmrsahklleVdzW\n"
		"PBAYMF4IqUlZLdd3jvGUsV+jhMy/2dnwXy5gfXiLoECRMC5O6Y39Wwiw/fhqLdFs\n"
		"U1ZTyEK3\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info server =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "1001",
	.fingerprint = "6c7238369943e8284deb16f5441485c2c3651230",
	.size_bits = 2048,
	.max_block_size = 256,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIEszCCA5ugAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyNDE0MjU0OFoX\n"
		"DTQ2MDUxOTE0MjU0OFowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC83R1rKHB0aPAD\n"
		"kDar8DAQJxWmC+F89pRt4qbWvDjBP2m/OjoNMoyt6Nj2VK6KYrd9ABveULX7xGP5\n"
		"fXQQSAM7pcKhWK1NT+jPfkfE7pFe3uQ2r6zniBDWPTZEaJDJKd0sqnR1fmLb/9Te\n"
		"PjLmEaflR55AdV9ud1NawH824ExCy6p6hVoVnYMdLk/P1VdhKT1PHMTaM/bfp6o9\n"
		"CYoEEEXLKjNBg5NgjQhc/c+uTxh9w3jJrxnGgFPrRNv2uybxoe+zALKR09G7PZKG\n"
		"FM/+6EE0HZQwMe3K+EJkipnFHegeCe//qbHTNpaH6sv7uyf/EYzMqVLPj6t4nJox\n"
		"E3d042UJAgMBAAGjggGEMIIBgDAJBgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQEAwIG\n"
		"QDAdBgNVHQ4EFgQUCsHwgTK7Ge+NspQ26h8wGvMMYdUwfQYDVR0jBHYwdIAUJOkK\n"
		"Q8ZDXLEBwgrPejxcBoAfUdahWKRWMFQxCzAJBgNVBAYTAkVFMRAwDgYDVQQIDAdF\n"
		"c3RvbmlhMQwwCgYDVQQKDANQQUwxDzANBgNVBAsMBlBBTCBDQTEUMBIGA1UEAwwL\n"
		"UEFMIFJvb3QgQ0GCAhAAMDQGA1UdEgQtMCuCDWNhLnBhbC5hbHQuZWWGGmh0dHBz\n"
		"Oi8vY2EucGFsLmFsdC5lZS9wYXRoMGcGA1UdEQRgMF6HBAECAwSHECABDbiFowAA\n"
		"AACKLgNwczSCDCoucGFsLmFsdC5lZYIRc2VydmVyLnBhbC5hbHQuZWWBCnBhbEBh\n"
		"bHQuZWWGF2h0dHBzOi8vcGFsLmFsdC5lZS9wYXRoMA4GA1UdDwEB/wQEAwIFoDAT\n"
		"BgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEAFdTfCF+eOTpg\n"
		"o/rMYq7AaeqtRsvE/qeBOwWmV1DQfckGlFSdg7GXIl71bI/K2rs98/b70+YojQZQ\n"
		"3vVNOGLef0/VE3aYSoyLLwWTS9kgPrP1sKPsYTjPet1UCEZ2zW6al75TIID7VFCn\n"
		"CNQV1BQeTcRvazqCFrdcQ+rLucKRZWfAoxwiqv3D3m+7JoiHXUlwXzN76nfOSfv3\n"
		"WIijpKn9d3FlqLL1Ygor9qyaY5IyXen11AIh8096HBl2hxjkzRrvtDuRBs3ZcXmY\n"
		"aBNsL5elNRc/BbxtWgfq2mbawx850sGUTO8P6ayTzB/ZPvnyZsfm04x1ZmPkTVke\n"
		"PplmsPF17A==\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info client =
{
	.version = 3,
	.common_name = "pal.alt.ee",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "1002",
	.fingerprint = "d29d1330c72cbe5142acff96054b95fdbeaecd4c",
	.size_bits = 2048,
	.max_block_size = 256,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIID6DCCAtCgAwIBAgICEAIwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCRUUx\n"
		"EDAOBgNVBAgMB0VzdG9uaWExDDAKBgNVBAoMA1BBTDEPMA0GA1UECwwGUEFMIENB\n"
		"MRwwGgYDVQQDDBNQQUwgSW50ZXJtZWRpYXRlIENBMB4XDTI2MDUyNDE0MjU0OFoX\n"
		"DTQ2MDUxOTE0MjU0OFowVTELMAkGA1UEBhMCRUUxEDAOBgNVBAgMB0VzdG9uaWEx\n"
		"DDAKBgNVBAoMA1BBTDERMA8GA1UECwwIUEFMIFRlc3QxEzARBgNVBAMMCnBhbC5h\n"
		"bHQuZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAs8QCDG6b2Mgq\n"
		"wcsodlz/t09Q4tumEilireAhluaF/Q5CY7UGZeABHjo65Pwi/tO6H0SmZyoTT99u\n"
		"rlD6fE/HKg8+g7b2wxg6a0BLVkNvCtbl7A24MyPSfnMm6vGVd6U7l9vqBG25My3t\n"
		"QdwJIvFtJieA/QNTjtpQIx9Fd5wKw13GA2OQkNUa0QkvgAR5NNcvkY8x/hliX4vP\n"
		"wFmTNhLmau7H2a4MTE9WLt4F7xgXOka8dFYz7xEVl7vVQxgch6ZKRN+OQmJbEBcy\n"
		"TXnslAJm1q3zTsFbFcvZTFSsQYnSvRgKqJEETLRS8K1NxWvqS/KjIvCO9TprQ9x9\n"
		"MIbKZtMDAgMBAAGjgbowgbcwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBaAw\n"
		"HQYDVR0OBBYEFN+65m2lpBl+jMlWO1USGpdemkcFMB8GA1UdIwQYMBaAFCTpCkPG\n"
		"Q1yxAcIKz3o8XAaAH1HWMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEF\n"
		"BQcDAgYIKwYBBQUHAwQwKAYDVR0RBCEwH4EKcGFsQGFsdC5lZYIRY2xpZW50LnBh\n"
		"bC5hbHQuZWUwDQYJKoZIhvcNAQELBQADggEBAAYaJoqq4FodxNAhLt1N/m/ZcypI\n"
		"vY0feit1qeS5/VssrS9JbWWJRGOCjY2dOoxAyTRgDW19t1/oYHVc8V2pDrJs3QPG\n"
		"K3mYxMeKxqDVqhMB5kS38wm+CO2Ss5mUEwc91A/LceKc08C84KOOoh5INuUjZ9EJ\n"
		"q/6GqEWJOONRZba8rd8lFWKVomNCb7ZoaYN9jKpv/sN7BDcG7EaYzFBjch4K23FT\n"
		"QU97rMy65Eyb0AQ/JIiZegWHU/wEYf/1EicmABwLsT8BcyhLA3XBa1brxMnqeenm\n"
		"jR1nCDZ4MuCZsvW+fSExuorFkjWmquTlnjRVe8Ct9dbg6417+3aiz7ZO/4I=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr info self_signed =
{
	.version = 3,
	.common_name = "Test",
	.subject_name = "",
	.subject_alternative_name = "",
	.issuer_name = "",
	.issuer_alternative_name = "",
	.serial_number = "14284e60a402cfbdb478d4b8f222b5ba1e105ee8",
	.fingerprint = "e35d0f166aa285a80fd64e68ff9d3294ff810747",
	.size_bits = 2048,
	.max_block_size = 256,
	.pem =
		"-----BEGIN CERTIFICATE-----\n"
		"MIIC/jCCAeagAwIBAgIUFChOYKQCz720eNS48iK1uh4QXugwDQYJKoZIhvcNAQEL\n"
		"BQAwDzENMAsGA1UEAwwEVGVzdDAgFw0yNjA1MjQxNDI1NDhaGA8yMTI2MDQzMDE0\n"
		"MjU0OFowDzENMAsGA1UEAwwEVGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\n"
		"AQoCggEBAOVsmiLf9sd/FSs+1T8th9H3o4oNWnWjJq1UTS8Socw7p7dxttXR8SCa\n"
		"3G+bDhb7fLAa0+VhcLCtivEzaq11UBeUeI3FjGpvRUG8x3ldB+mFPLdQWqSaY6/p\n"
		"8E5o8sl3qP24fFltjygxxWnng8LbqLq8uyJKn/Owxw0Zk629NcYWiA5jOLdApkRn\n"
		"5vTJrOk+MhcAodNed2JhT9D+PFjiherHeRFWZBbr6oaSdc7gO1QwGDSSGQ+2LWpq\n"
		"IzfV8bURI/5XnYWd8TaRGsbDcRodTACKcIxpzCGV6Dfrv2MqIuCkYIIZx+ZTjNKk\n"
		"0P/xa6JXKAlMsF5eqUwfv9JSB1SJxF0CAwEAAaNQME4wDgYDVR0PAQH/BAQDAgWg\n"
		"MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQU+2ZwsT3g\n"
		"CmXOikngTG4ioFflLhswDQYJKoZIhvcNAQELBQADggEBABMCRxhoafBqnAYvp9BG\n"
		"4QReQlTVPvtYQGBN08AU3QYmCGEzuxvdBJnDuPdYTka/9T78p2B8yiLFcOB9VXc+\n"
		"oNMDpJw6Nfj3NYEHPrx0wAzixx7EIpyBUlKN9FlqzvOOKuiWALnj+jaH2i7z5+oH\n"
		"yuRFM2tWeTYVXEAveuqr/mg5bG4XH40+zm02MMU2C8nhmUUsiffmYthLhdfGmafz\n"
		"Z3qqOXO1q7LWUweQtnieg40prPhj+uq4aGMyN91f7KWnLqOnk8a3w6nQ+UneB8f8\n"
		"ThKfYFtziL6vswQl/41Y0Fz/hagYrDXgu70rFae8vckuSSuHepCc3KG69aO7heaf\n"
		"30Q=\n"
		"-----END CERTIFICATE-----\n",
};

constexpr const info *data[] = { &ca, &intermediate, &server, &client, &self_signed };

} // namespace pal_test::cert
