if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
	include(cmake/cxx/gnu.cmake)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	include(cmake/cxx/clang.cmake)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
	include(cmake/cxx/msvc.cmake)
else()
	message(FATAL_ERROR "Unsupported compiler")
endif()

include(cmake/cxx/benchmark.cmake)
include(cmake/cxx/doc.cmake)
include(cmake/cxx/executable.cmake)
include(cmake/cxx/library.cmake)
include(cmake/cxx/test.cmake)
