on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [macos, ubuntu]
        compiler: [clang, gcc]
        include:
          - os: windows
            compiler: msvc

    steps:
      - uses: actions/checkout@v2

      - if: matrix.compiler == 'gcc'
        run: |
          echo "::set-env name=CC::gcc-9"
          echo "::set-env name=CXX::g++-9"
          echo "::set-env name=CMAKE_BUILD_GENERATOR::'Ninja Multi-Config'"

      - if: matrix.compiler == 'clang'
        run: |
          echo "::set-env name=CC::clang"
          echo "::set-env name=CXX::clang++"
          echo "::set-env name=CMAKE_BUILD_GENERATOR::'Ninja Multi-Config'"

      - if: matrix.compiler == 'msvc'
        run: |
          echo "::set-env name=CMAKE_BUILD_GENERATOR::'Visual Studio 15 2017 Win64'"

      - run: |
          echo "CMAKE_BUILD_GENERATOR=${CMAKE_BUILD_GENERATOR}"
