on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            env:
              CC=gcc-9
              CXX=g++-9
          - os: macos-latest
            env:
              CC=clang
              CXX=clang++
          - os: ubuntu-latest
            env:
              CC=gcc-9
              CXX=g++-9
          - os: ubuntu-latest
            env:
              CC=clang
              CXX=clang++
          - os: windows-latest

    steps:
      - run: |
          echo CC=$CC CXX=$CXX
          $CC --version
