name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y g++-14 libc++-18-dev libc++abi-18-dev
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14
      - run: ninja all

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ninja all

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: ninja all
