name: Coverage

on:
  push:
    branches: [main, github_actions]

jobs:
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y llvm

      - name: Build, test, and generate coverage
        run: ninja coverage

      - name: Coverage summary
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          llvm-cov report .build/linux-clang-coverage/pal_test \
            -instr-profile=.build/linux-clang-coverage/coverage.profdata \
            --Xdemangler=c++filt \
            --Xdemangler=-n \
            "-ignore-filename-regex=.*(test|bench)\.cpp$" \
            "-ignore-filename-regex=.*/test\.(cpp|hpp)$" \
            "-ignore-filename-regex=.*\.build/.*" \
            >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
