name: Documentation

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          sudo apt-get install --yes cmake
          cmake . -DCMAKE_BUILD_TYPE=Coverage -Dpal_docs=yes -Dpal_unittests=no

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          publish_branch: gh-pages
