name: Lint

on:
  push:
    branches: [main, github_actions]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang-tidy
          if ! command -v run-clang-tidy >/dev/null; then
            sudo ln -sf "$(ls /usr/bin/run-clang-tidy-* | sort -V | tail -1)" /usr/local/bin/run-clang-tidy
          fi

      - run: ninja format-check
      - run: ninja tidy
