name: Lint

on:
  push:
    branches: [main, github_actions]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang-tidy-20 libc++-18-dev libc++abi-18-dev
          sudo ln -sf /usr/bin/run-clang-tidy-20 /usr/bin/run-clang-tidy
          sudo ln -sf /usr/bin/clang-tidy-20 /usr/bin/clang-tidy

      - run: ninja tidy
