name: Sanitize

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sanitize:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get install -y g++-14
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14
      - run: ninja sanitize
